version: 2

sphinx:
  configuration: docs/read_the_docs/source/conf.py

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.11"

python:
  install:
    - requirements: docs/read_the_docs/requirements.txt
