# frozen_string_literal: true

source 'http://rubygems.org'

gem 'ci_reporter_minitest', '~> 1.0.0'
gem 'codecov'
gem 'minitest', '~> 5.9'
gem 'minitest-ci' # For CircleCI Automatic test metadata collection
gem 'minitest-reporters'
gem 'nokogiri', '~> 1.10'
gem 'oga'
gem 'rake'
gem 'schematron-nokogiri', git: 'http://github.com/shorowit/schematron.git', branch: 'return_context_path'
gem 'simplecov'
