source "http://rubygems.org"

# simplecov has a dependency on native json gem, use fork that does not require this
gem 'simplecov', github: 'NREL/simplecov'

gem 'urbanopt-scenario', '0.1.0'
gem 'urbanopt-geojson', '0.1.0'
gem 'openstudio-standards', '0.2.10'
