# frozen_string_literal: true

module Constants
  Auto = 'auto'
  Heating = 'heating'
  Cooling = 'cooling'
  Weekday = 'weekday'
  Weekend = 'weekend'

  # Exclude these BuildResidentialHPXML arguments as ResStockArguments arguments
  BuildResidentialHPXMLExcludes = ['hpxml_path',
                                   'existing_hpxml_path',
                                   'whole_sfa_or_mf_building_sim',
                                   'software_info_program_used',
                                   'software_info_program_version',
                                   'schedules_filepaths',
                                   'schedules_unavailable_period_types',
                                   'schedules_unavailable_period_dates',
                                   'schedules_unavailable_period_window_natvent_availabilities',
                                   'simulation_control_timestep',
                                   'simulation_control_run_period',
                                   'simulation_control_run_period_calendar_year',
                                   'simulation_control_daylight_saving_period',
                                   'simulation_control_temperature_capacitance_multiplier',
                                   'simulation_control_defrost_model_type',
                                   'simulation_control_onoff_thermostat_deadband',
                                   'simulation_control_heat_pump_backup_heating_capacity_increment',
                                   'unit_multiplier',
                                   'geometry_unit_height_above_grade',
                                   'geometry_unit_left_wall_is_adiabatic',
                                   'geometry_unit_right_wall_is_adiabatic',
                                   'geometry_unit_front_wall_is_adiabatic',
                                   'geometry_unit_back_wall_is_adiabatic',
                                   'geometry_unit_num_floors_above_grade',
                                   'air_leakage_has_flue_or_chimney_in_conditioned_space',
                                   'heating_system_airflow_defect_ratio',
                                   'cooling_system_airflow_defect_ratio',
                                   'cooling_system_charge_defect_ratio',
                                   'heat_pump_airflow_defect_ratio',
                                   'heat_pump_charge_defect_ratio',
                                   'hvac_control_heating_weekday_setpoint',
                                   'hvac_control_heating_weekend_setpoint',
                                   'hvac_control_cooling_weekday_setpoint',
                                   'hvac_control_cooling_weekend_setpoint',
                                   'pv_system_num_bedrooms_served',
                                   'battery_num_bedrooms_served',
                                   'vehicle_battery_capacity',
                                   'vehicle_hours_driven_per_week',
                                   'misc_plug_loads_vehicle_usage_multiplier',
                                   'misc_plug_loads_vehicle_2_usage_multiplier',
                                   'misc_plug_loads_vehicle_annual_kwh',
                                   'misc_plug_loads_vehicle_present',
                                   'electric_panel_service_feeders_load_calculation_types',
                                   'electric_panel_baseline_peak_power',
                                   'electric_panel_service_voltage',
                                   'electric_panel_service_max_current_rating',
                                   'electric_panel_breaker_spaces_headroom',
                                   'electric_panel_breaker_spaces_rated_total',
                                   'electric_panel_load_heating_system_power_rating',
                                   'electric_panel_load_cooling_system_power_rating',
                                   'electric_panel_load_heat_pump_power_rating',
                                   'electric_panel_load_heating_system_2_power_rating',
                                   'electric_panel_load_mech_vent_power_rating',
                                   'electric_panel_load_mech_vent_2_power_rating',
                                   'electric_panel_load_whole_house_fan_power_rating',
                                   'electric_panel_load_kitchen_fans_power_rating',
                                   'electric_panel_load_bathroom_fans_power_rating',
                                   'electric_panel_load_electric_water_heater_power_rating',
                                   'electric_panel_load_electric_clothes_dryer_power_rating',
                                   'electric_panel_load_dishwasher_power_rating',
                                   'electric_panel_load_electric_cooking_range_power_rating',
                                   'electric_panel_load_misc_plug_loads_well_pump_power_rating',
                                   'electric_panel_load_misc_plug_loads_vehicle_power_rating',
                                   'electric_panel_load_pool_pump_power_rating',
                                   'electric_panel_load_electric_pool_heater_power_rating',
                                   'electric_panel_load_permanent_spa_pump_power_rating',
                                   'electric_panel_load_electric_permanent_spa_heater_power_rating',
                                   'electric_panel_load_other_power_rating',
                                   'electric_panel_load_heat_pump_voltage',
                                   'electric_panel_load_electric_water_heater_voltage',
                                   'electric_panel_load_electric_clothes_dryer_voltage',
                                   'electric_panel_load_electric_cooking_range_voltage',
                                   'electric_panel_load_misc_plug_loads_vehicle_voltage',
                                   'electric_panel_load_heating_system_new_load',
                                   'electric_panel_load_cooling_system_new_load',
                                   'electric_panel_load_heat_pump_new_load',
                                   'electric_panel_load_heating_system_2_new_load',
                                   'electric_panel_load_mech_vent_fan_new_load',
                                   'electric_panel_load_mech_vent_2_new_load',
                                   'electric_panel_load_whole_house_fan_new_load',
                                   'electric_panel_load_kitchen_fans_new_load',
                                   'electric_panel_load_bathroom_fans_new_load',
                                   'electric_panel_load_electric_water_heater_new_load',
                                   'electric_panel_load_electric_clothes_dryer_new_load',
                                   'electric_panel_load_dishwasher_new_load',
                                   'electric_panel_load_electric_cooking_range_new_load',
                                   'electric_panel_load_misc_plug_loads_well_pump_new_load',
                                   'electric_panel_load_misc_plug_loads_vehicle_new_load',
                                   'electric_panel_load_pool_pump_new_load',
                                   'electric_panel_load_electric_pool_heater_new_load',
                                   'electric_panel_load_permanent_spa_pump_new_load',
                                   'electric_panel_load_electric_permanent_spa_heater_new_load',
                                   'electric_panel_load_other_new_load',
                                   'emissions_scenario_names',
                                   'emissions_types',
                                   'emissions_electricity_units',
                                   'emissions_electricity_values_or_filepaths',
                                   'emissions_electricity_number_of_header_rows',
                                   'emissions_electricity_column_numbers',
                                   'emissions_fossil_fuel_units',
                                   'emissions_natural_gas_values',
                                   'emissions_propane_values',
                                   'emissions_fuel_oil_values',
                                   'emissions_wood_values',
                                   'emissions_coal_values',
                                   'emissions_wood_pellets_values',
                                   'utility_bill_scenario_names',
                                   'utility_bill_electricity_filepaths',
                                   'utility_bill_electricity_fixed_charges',
                                   'utility_bill_electricity_marginal_rates',
                                   'utility_bill_natural_gas_fixed_charges',
                                   'utility_bill_natural_gas_marginal_rates',
                                   'utility_bill_propane_fixed_charges',
                                   'utility_bill_propane_marginal_rates',
                                   'utility_bill_fuel_oil_fixed_charges',
                                   'utility_bill_fuel_oil_marginal_rates',
                                   'utility_bill_wood_fixed_charges',
                                   'utility_bill_wood_marginal_rates',
                                   'utility_bill_coal_fixed_charges',
                                   'utility_bill_coal_marginal_rates',
                                   'utility_bill_wood_pellets_fixed_charges',
                                   'utility_bill_wood_pellets_marginal_rates',
                                   'utility_bill_pv_compensation_types',
                                   'utility_bill_pv_net_metering_annual_excess_sellback_rate_types',
                                   'utility_bill_pv_net_metering_annual_excess_sellback_rates',
                                   'utility_bill_pv_feed_in_tariff_rates',
                                   'utility_bill_pv_monthly_grid_connection_fee_units',
                                   'utility_bill_pv_monthly_grid_connection_fees',
                                   'additional_properties',
                                   'combine_like_surfaces',
                                   'apply_defaults',
                                   'apply_validation']

  # Exclude these BuildResidentialScheduleFile arguments as ResStockArguments arguments
  BuildResidentialScheduleFileExcludes = ['hpxml_path',
                                          'schedules_column_names',
                                          'schedules_random_seed',
                                          'output_csv_path',
                                          'hpxml_output_path',
                                          'append_output',
                                          'debug',
                                          'building_id']

  # Exclude these ResStockArguments from being required in options_lookup.tsv
  # These are arguments added to ResStockArguments not in BuildResidentialHPXML
  OtherExcludes = ['building_id',
                   'heating_system_actual_cfm_per_ton',
                   'heating_system_rated_cfm_per_ton']

  # List of ResStockArguments arguments; reported as build_existing_model.<argument_name>, ...
  ArgumentsToRegister = ['heating_unavailable_period',
                         'cooling_unavailable_period',
                         'electric_panel_service_max_current_rating_bin',
                         'electric_panel_service_max_current_rating']

  # List of ResStockArguments arguments; will not be passed into BuildResidentialHPXML
  ArgumentsToExclude = ['heating_unavailable_period',
                        'cooling_unavailable_period',
                        'electric_panel_service_max_current_rating_bin']
end
