name: Install Python dependencies

on:
  # Run on weeknights or on-demand from GitHub
  push:
  workflow_dispatch:
  # schedule:
  #   # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
  #   # 5:24 am UTC (11:24pm MDT the day before) every weekday night in MDT
    # - cron: '24 5 * * 2-6'
  # pull_request:
    # types: [review_requested]

env:
  # Favor_Local_Gems enforces develop branch of all Ruby dependencies
  # This is our canary in the coal mine! If any simulation tests fail, comment this and retry.
  # If CI is then successful, we have a breaking change in a dependency somewhere.
  FAVOR_LOCAL_GEMS: true
  GEM_DEVELOPER_KEY: ${{ secrets.GEM_DEVELOPER_KEY }}
  UO_NUM_PARALLEL: 4
  # GHA machines have 4 cores. Trying to run more concurrently will slow everything down.
  # https://github.blog/2024-01-17-github-hosted-runners-double-the-power-for-open-source/

jobs:
  install:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    # container:
    #   image: docker://nrel/openstudio:3.7.0
    steps:
      - uses: actions/checkout@v4
      - name: Change Owner of Container Working Directory
      # working dir permissions workaround from https://github.com/actions/runner-images/issues/6775#issuecomment-1377299658
        run: chown root:root .
      - name: Install Ruby dependencies
        run: |
          ruby --version
          bundle update
          bundle exec certified-update
      - name: Install python dependencies
        run: bundle exec rspec -e 'Install python dependencies'
